sdl2:
	$(MAKE) -C SDL2/ all

glut:
	$(MAKE) -C OPENGL_GLUT/ all

glew:
	$(MAKE) -C OPENGL_GLEW/ all

all: glew glut sdl2

clean:
	$(MAKE) -C SDL2/ clean
	$(MAKE) -C OPENGL_GLUT/ clean
	$(MAKE) -C OPENGL_GLEW/ clean
