all:
	mkdir bin
	g++ simple.cpp -lGL -lGLU -lglut -o bin/OPENGL_GLUT_default
	g++ rects.cpp -lGL -lGLU -lglut -o bin/OPENGL_GLUT_rects
	g++ image.cpp -lGL -lGLU -lglut -lSOIL -o bin/OPENGL_GLUT_image
	

clean:
	rm -rf bin
